### ISSUE TITLE
Support for integer and booleans parameters

### ISSUE THREAD

**Issue by waredjeb** [cms-patatrack/The-Optimizer#17]
To think about it: would it make sense to add support for integer and booleans parameter? Currently all the parameters are extracted "continously" in a certain range. In the case the parameters are integers or booleans one could always `round` the generated parameters, but that means the optimizer would generate a lot of useless parameter.

**Comment by rsreds** [comment]
This is a big one.
Changing the data type would affect a lot of the code.
However in case of categorical data (i.e. bool) PSO is not the best fit, so probably would make sense to consider this for a future extension.

**Comment by rsreds** [comment]
Reopened after reset #26
