### ISSUE TITLE
Reduce arguments in MOPSO

### ISSUE THREAD

**Issue by rsreds** [cms-patatrack/The-Optimizer#5]
Too many arguments and attributes:

- [x] move `num_iterations` to optimize function
- [x] move `max_iter_no_improv` to optimize function

**Comment by waredjeb** [comment]
@rsreds Am I wrong or `optimization_mode` doesn't make sense anymore? There's no difference in the `optimize()` function. Right?

**Comment by rsreds** [comment]
You are right, I thought I removed it everywhere
